# Generated by Django 3.2.8 on 2021-11-01 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('isComplete', models.BooleanField(default=False)),
                ('multipleorder', models.BooleanField(default=True)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=150)),
                ('hotelloc', models.CharField(max_length=150)),
                ('hotelphone', models.IntegerField()),
                ('open', models.BooleanField(default=False)),
                ('logo', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('itemname', models.CharField(max_length=150)),
                ('itemprice', models.PositiveIntegerField()),
                ('itemdesc', models.TextField()),
                ('itemphoto', models.CharField(max_length=550)),
                ('itemrating', models.PositiveIntegerField()),
                ('itemtrending', models.BooleanField(default=False)),
                ('quarter', models.BooleanField(default=False)),
                ('quarterprice', models.PositiveIntegerField(blank=True, null=True)),
                ('half', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('halfprice', models.PositiveIntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('street', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('orderTime', models.TimeField(auto_now_add=True)),
                ('paymentmethod', models.CharField(max_length=6)),
                ('order_status', models.CharField(choices=[('0', '0'), ('0', '1'), ('1', '2'), ('2', '3'), ('3', '4'), ('4', '5')], default='0', max_length=1)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=8)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('hotelname', models.CharField(max_length=150)),
                ('cartitemname', models.CharField(max_length=200)),
                ('hotellocation', models.CharField(max_length=300)),
                ('itemid', models.CharField(max_length=250)),
                ('cartid', models.CharField(max_length=250)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.cart')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('product', models.ManyToManyField(to='hotels.Items')),
            ],
        ),
    ]
