# Generated by Django 3.2.8 on 2021-11-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='order_cancel_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CANCEL', 'CANCEL'), ('ORDER COMPLETE', 'ORDER COMPLETE'), ('ORDER RECIEVED', 'ORDER RECIEVED'), ('PROCESSING', 'PROCESSING'), ('PICKEDUP', 'PICKEDUP'), ('DELIVERED', 'DELIVERED')], default='ORDER COMPLETE', max_length=14),
        ),
    ]
