# Generated by Django 3.2.8 on 2021-11-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20211101_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='order_cancel_status',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_cancel_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
