# Generated by Django 3.2.8 on 2021-11-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20211101_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='razorpay_payment_id',
        ),
    ]
